In [1]:
# Load libraries

import pandas as pd
import numpy as np
import re
import requests 
from bs4 import BeautifulSoup 
import plotly.express as px

In [2]:
# assign the url to scrape

URL = "https://www.forbes.com/sites/mikeozanian/2021/05/07/worlds-most-valuable-sports-teams-2021/?sh=1af1ab253e9e"
r = requests.get(URL) 

soup = BeautifulSoup(r.content, 'html5lib') 
#print(soup.prettify())

In [3]:
data = []
for s in soup.find_all("strong"):
    data.append(''.join(s.get_text()))

In [4]:
df = pd.DataFrame(np.array_split(data[2:-2], 50),
            columns=['club','value','five_year_change_in_value','owner','year_purchased','price_paid'])

In [5]:
df.head(50)

,club,value,five_year_change_in_value,owner,year_purchased,price_paid
0,1. Dallas Cowboys (NFL),$5.7 billion,43%,Jerry Jones,1989,$150 million
1,2. New York Yankees (MLB),$5.25 billion,54%,Steinbrenner family,1973,$8.8 million
2,3. New York Knicks (NBA),$5 billion,67%,Madison Square Garden Sports,1997,$300 million
3,4. Barcelona (Soccer),$4.76 billion,34%,club members,not applicable,not applicable
4,5. Real Madrid (Soccer),$4.75 billion,30%,club members,not applicable,not applicable
5,6. Golden State Warriors (NBA),$4.7 billion,147%,"Joe Lacob, Peter Gruber",2010,$450 million
6,7. Los Angeles Lakers (NBA),$4.6 billion,70%,"Jerry Buss Family Trusts, Philip Anschutz","1979, 1998","$20 million, $268 million"
7,8. New England Patriots (NFL),$4.4 billion,38%,Robert Kraft,1994,$172 million
8,9. New York Giants (NFL),$4.3 billion,54%,"John Mara, Steven Tisch","1925, 1991","$500, $150 million"
9,10. Bayern Munich (Soccer),$4.21 billion,57%,club members,not applicable,not applicable
10,11. Manchester United (Soccer),$4.2 billion,27%,Glazer family,2005,$1.4 billion
11,12. Liverpool (Soccer),$4.1 billion,165%,"John Henry, Tom Werner",2010,$476 million
12,13 (tie). Los Angeles Rams (NFL),$4 billion,176%,Stanley Kroenke,2010,$750 million
13,13 (tie). Manchester City (Soccer),$4 billion,108%,heikh Mansour bin Zayed Al Nahyan,2008,$385 million
14,15. San Francisco 49ers (NFL),$3.8 billion,41%,"Denise DeBartolo York, John York",1977,$13 million
15,16. Los Angeles Dodgers (MLB),$3.57 billion,43%,Guggenheim Baseball Management,2012,$2 billion
16,17. New York Jets (NFL),$3.55 billion,37%,Johnson family,2000,$635 million
17,18. Chicago Bears (NFL),$3.53 billion,44%,McCaskey family,1920,$100
18,19. Washington Football Team (NFL),$3.5 billion,23%,Daniel Snyder,1999,$750 million
19,20. Boston Red Sox (MLB),$3.47 billion,51%,"John Henry, Tom Werner",2002,$380 million
20,21. Philadelphia Eagles (NFL),$3.4 billion,42%,Jeffrey Lurie,1994,$185 million
21,22. Chicago Cubs (MLB),$3.36 billion,53%,Ricketts family,2009,$700 million
22,23 (tie). Houston Texans (NFL),$3.3 billion,32%,Janice McNair,1999,$700 million
23,23 (tie). Chicago Bulls (NBA),$3.3 billion,43%,Jerry Reinsdorf,1985,$16.2 million
24,25 (tie). Denver Broncos (NFL),$3.2 billion,65%,Pat Bowlen Trust,1984,$78 million
25,25 (tie). Boston Celtics (NBA),$3.2 billion,52%,"Wycliffe Grousbeck, Irving Grousbeck, Robert E...",2002,$360 million
26,25 (tie). Chelsea (Soccer),$3.2 billion,93%,Roman Abramovich,2003,$233 million
27,28. San Francisco Giants (MLB),$3.18 billion,41%,Charles Johnson,1993,$100 million
28,29. Las Vegas Raiders (NFL),$3.1 billion,117%,Mark Davis,1966,"$180,000"
29,30. Seattle Seahawks (NFL),$3.08 billion,64%,Paul G. Allen Trust,1997,$194 million
30,31. Green Bay Packers (NFL),$3.05 billion,56%,shareholders,1921,$100
31,32. Pittsburgh Steelers (NFL),$3 billion,58%,"Daniel Rooney Trust, Arthur Rooney II",1933,"$2,500"
32,33. Baltimore Ravens (NFL),$2.98 billion,54%,Stephen Bisciotti,2004,$600 million
33,34. Minnesota Vikings (NFL),$2.95 billion,86%,Zygmunt Wilf,2005,$600 million
34,35. Miami Dolphins (NFL),$2.9 billion,57%,Stephen Ross,2009,1.1 billion
35,36. Atlanta Falcons (NFL),$2.88 billion,72%,Arthur Blank,2002,$545 million
36,37. Indianapolis Colts (NFL),2.85 billion,52%,James Irsay,1972,$14 million
37,38. Arsenal (Soccer),$2.8 billion,39%,Stanley Kroenke,2011,$1.1 billion
38,39. Los Angeles Clippers (NBA),$2.75 billion,38%,Steve Ballmer,2014,$2 billion
39,40. Brooklyn Nets (NBA),$2.65 billion,56%,Joseph Tsai,2019,$3.2 billion
40,41. Los Angeles Chargers (NFL),$2.6 billion,70%,Dean Spanos,1984,$72 million
41,42. Carolina Panthers (NFL),$2.55 billion,63%,David Tepper,2018,$2.28 billion
42,43 (tie). Kansas City Chiefs (NFL),$2.5 billion,63%,Hunt family,1960,"$25,000"
43,43 (tie). Houston Rockets (NBA),$2.5 billion,67%,Tilman Fertitta,2017,$2.2 billion
44,43 (tie). Paris Saint-Germain (Soccer),$2.5 billion,207%,Qatar Sports Investments,2011,$100 million
45,46. New Orleans Saints (NFL),$2.48 billion,63%,Gayle Benson,1985,$70.2 million
46,47 (tie). Jacksonville Jaguars (NFL),$2.45 billion,66%,Shahid Khan,2011,$770 million
47,47 (tie). New York Mets (MLB),$2.45 billion,48%,Steve Cohen,2020,$2.42 billion
48,47 (tie). Dallas Mavericks (NBA),$2.45 billion,75%,Mark Cuban,2000,$280 million
49,50. Cleveland Browns (NFL),$2.35 billion,57%,ee and Jimmy Haslam,2012,$987 million